require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AmaExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-ama', :path => '../..'

  arm_value = `/usr/sbin/sysctl -n hw.optional.arm64 2>&1`.to_i

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      if arm_value == 1 then
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      else
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = ""
      end
    end
  end
end
