import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
