name: Run Tests

on:
  pull_request:
  push:
    branches: main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: TypeScript Check
        run: yarn ts:check

      # - name: Core Tests
      #   run: yarn test
